# Indicator definitions for the Market Stress Monitor

# Indicators included in the composite stress score
COMPOSITE_INDICATORS = {
    "vix": {
        "fred_series": "VIXCLS",
        "name": "VIX Volatility Index",
        "category": "Volatility",
        "weight": 0.15,
        "higher_is_stress": True,
        "unit": "Index",
        "description": "CBOE Volatility Index — equity market fear gauge",
        "fmt": ".1f",
    },
    "hy_spread": {
        "fred_series": "BAMLH0A0HYM2",
        "name": "HY Credit Spread",
        "category": "Credit",
        "weight": 0.20,
        "higher_is_stress": True,
        "unit": "%",
        "description": "ICE BofA US High Yield OAS — CDS market proxy (FRED reports in %, e.g. 3.2 = 320 bps)",
        "fmt": ".2f",
    },
    "ig_spread": {
        "fred_series": "BAMLC0A0CM",
        "name": "IG Credit Spread",
        "category": "Credit",
        "weight": 0.10,
        "higher_is_stress": True,
        "unit": "%",
        "description": "ICE BofA US Investment Grade OAS (FRED reports in %, e.g. 1.0 = 100 bps)",
        "fmt": ".2f",
    },
    "yield_curve": {
        "fred_series": "T10Y2Y",
        "name": "Yield Curve (2s10s)",
        "category": "Rates",
        "weight": 0.10,
        "higher_is_stress": False,  # Inversion (negative) = stress
        "unit": "%",
        "description": "10Y minus 2Y Treasury spread — inversion signals recession risk",
        "fmt": ".2f",
    },
    "nfci": {
        "fred_series": "NFCI",
        "name": "Fin. Conditions (NFCI)",
        "category": "Conditions",
        "weight": 0.20,
        "higher_is_stress": True,
        "unit": "Index",
        "description": "Chicago Fed NFCI — positive = tighter than average",
        "fmt": ".3f",
    },
    "stlfsi": {
        "fred_series": "STLFSI4",
        "name": "Fin. Stress (STLFSI)",
        "category": "Conditions",
        "weight": 0.15,
        "higher_is_stress": True,
        "unit": "Index",
        "description": "St. Louis Fed Financial Stress Index — positive = above-average stress",
        "fmt": ".3f",
    },
    "sp500_drawdown": {
        "fred_series": None,
        "yf_ticker": "^GSPC",
        "name": "S&P 500 Drawdown",
        "category": "Equity",
        "weight": 0.10,
        "higher_is_stress": False,  # More negative = more stress
        "unit": "%",
        "description": "S&P 500 drawdown from 52-week high",
        "fmt": ".1f",
    },
}

# Displayed alongside composite indicators but not included in the score
INFORMATIONAL_INDICATORS = {
    "sofr": {
        "fred_series": "SOFR",
        "name": "SOFR",
        "category": "Funding",
        "unit": "%",
        "description": "Secured Overnight Financing Rate",
        "fmt": ".2f",
    },
    "effr": {
        "fred_series": "DFF",
        "name": "Fed Funds Rate",
        "category": "Rates",
        "unit": "%",
        "description": "Effective Federal Funds Rate",
        "fmt": ".2f",
    },
    "t2y": {
        "fred_series": "GS2",
        "name": "2Y Treasury",
        "category": "Rates",
        "unit": "%",
        "description": "2-Year Treasury Constant Maturity Rate",
        "fmt": ".2f",
    },
    "t10y": {
        "fred_series": "GS10",
        "name": "10Y Treasury",
        "category": "Rates",
        "unit": "%",
        "description": "10-Year Treasury Constant Maturity Rate",
        "fmt": ".2f",
    },
    "breakeven": {
        "fred_series": "T10YIE",
        "name": "10Y Breakeven Inflation",
        "category": "Rates",
        "unit": "%",
        "description": "10-Year Treasury Breakeven Inflation Rate",
        "fmt": ".2f",
    },
    "lending_stds": {
        "fred_series": "DRTSCILM",
        "name": "Bank Lending Standards",
        "category": "Credit",
        "unit": "%",
        "description": "Net % of banks tightening C&I standards (quarterly)",
        "fmt": ".1f",
    },
    "fear_greed": {
        "fred_series": None,
        "name": "CNN Fear & Greed Index",
        "category": "Sentiment",
        "unit": "Index",
        "description": "CNN Fear & Greed Index: 0 = Extreme Fear, 100 = Extreme Greed",
        "fmt": ".0f",
    },
    "rrpontsyd": {
        "fred_series": "RRPONTSYD",
        "name": "Overnight Reverse Repo (ON RRP)",
        "category": "Funding",
        "unit": "$ Bn",
        "description": "Fed overnight reverse repo facility usage — excess liquidity parked at the Fed",
        "fmt": ".0f",
    },
    "dpcredit": {
        "fred_series": "DPCREDIT",
        "name": "Discount Window Rate",
        "category": "Funding",
        "unit": "%",
        "description": "Fed Primary Credit Rate — emergency lending to banks; spikes signal acute stress (SVB, 2008)",
        "fmt": ".2f",
    },
    "wresbal": {
        "fred_series": "WRESBAL",
        "name": "Bank Reserves at Fed",
        "category": "Funding",
        "unit": "$ Bn",
        "description": "Total reserve balances maintained at Federal Reserve Banks — system-wide liquidity cushion",
        "fmt": ".0f",
    },
    "t10y3m": {
        "fred_series": "T10Y3M",
        "name": "10Y-3M Yield Spread",
        "category": "Rates",
        "unit": "%",
        "description": "10Y minus 3-Month Treasury spread — preferred by Fed researchers as recession predictor",
        "fmt": ".2f",
    },
    "t30y": {
        "fred_series": "DGS30",
        "name": "30Y Treasury",
        "category": "Rates",
        "unit": "%",
        "description": "30-Year Treasury Constant Maturity Rate — long-end term premium signal",
        "fmt": ".2f",
    },
    "baa10y": {
        "fred_series": "BAA10Y",
        "name": "Moody's Baa-10Y Spread",
        "category": "Credit",
        "unit": "%",
        "description": "Moody's Baa Corporate Bond Yield minus 10Y Treasury — independent CDS proxy",
        "fmt": ".2f",
    },
    "vxv": {
        "fred_series": "VXVCLS",
        "name": "3-Month VIX (VXVCLS)",
        "category": "Volatility",
        "unit": "Index",
        "description": "CBOE S&P 500 3-Month Implied Volatility — longer-dated fear vs. the 1-month VIX",
        "fmt": ".1f",
    },
    "cc_delinquency": {
        "fred_series": "DRCCLACBS",
        "name": "Credit Card Delinquency Rate",
        "category": "Consumer Credit",
        "unit": "%",
        "description": "Delinquency rate on credit card loans, all commercial banks — quarterly, released ~3 months after quarter-end. Rising trend signals consumer financial stress.",
        "fmt": ".2f",
    },
    "consumer_credit": {
        "fred_series": "TOTALSL",
        "name": "Total Consumer Credit",
        "category": "Consumer Credit",
        "unit": "$ Bn",
        "description": "Total outstanding consumer credit (revolving + non-revolving, SA) — monthly, released ~6 weeks after month-end. Rapid expansion signals overleveraging risk.",
        "fmt": ".0f",
    },
    "revolving_credit": {
        "fred_series": "REVOLSL",
        "name": "Revolving Credit (Credit Cards)",
        "category": "Consumer Credit",
        "unit": "$ Bn",
        "description": "Outstanding revolving consumer credit, mostly credit cards (SA) — monthly, released ~6 weeks after month-end. Level and trend proxy household balance-sheet stress.",
        "fmt": ".0f",
    },
    "dxy": {
        "fred_series": "DTWEXBGS",
        "name": "US Dollar Index (Broad)",
        "category": "FX & Commodities",
        "unit": "Index",
        "description": "Nominal Broad US Dollar Index — surges during risk-off / flight-to-safety episodes",
        "fmt": ".1f",
    },
    "wti": {
        "fred_series": "DCOILWTICO",
        "name": "WTI Crude Oil",
        "category": "FX & Commodities",
        "unit": "$/bbl",
        "description": "WTI crude oil spot price — falls sharply during demand destruction / recession fears",
        "fmt": ".1f",
    },
    "copper_gold_ratio": {
        "fred_series": None,
        "name": "Copper / Gold Ratio",
        "category": "FX & Commodities",
        "unit": "ratio",
        "description": "Copper futures ÷ Gold futures — rising = risk-on / economic optimism; falling = recession fear as gold outperforms copper",
        "fmt": ".4f",
    },
    "m2": {
        "fred_series": "M2SL",
        "name": "M2 Money Supply",
        "category": "Money Supply",
        "unit": "$ Bn",
        "description": "M2 money supply (monthly, SA) — includes cash, checking, savings, and money market funds. Rapid expansion signals potential inflation pressure.",
        "fmt": ".0f",
    },
    "m2_yoy": {
        "fred_series": None,
        "name": "M2 Growth (YoY %)",
        "category": "Money Supply",
        "unit": "%",
        "description": "Year-over-year percent change in M2 — computed from FRED M2SL. Negative readings are historically rare and have preceded recessions (most recently 2022-2023).",
        "fmt": ".1f",
    },
    "m1": {
        "fred_series": "M1SL",
        "name": "M1 Money Supply",
        "category": "Money Supply",
        "unit": "$ Bn",
        "description": "M1 money supply (monthly, SA) — most liquid money: cash, demand deposits, and other checkable deposits. Reflects immediate liquidity conditions.",
        "fmt": ".0f",
    },
    "jobless_claims": {
        "fred_series": "ICSA",
        "name": "Initial Jobless Claims",
        "category": "Labor",
        "unit": "Thousands",
        "description": "Weekly initial unemployment claims (seasonally adjusted) — spikes precede recessions",
        "fmt": ".0f",
    },
}

# Years of history to fetch and normalize against
LOOKBACK_YEARS = 7

# Rolling window (in trading days) used for historical stress chart
ROLLING_NORM_WINDOW = 504  # ~2 years

STRESS_BANDS = [
    (0, 25, "Low", "#27ae60"),
    (25, 45, "Moderate", "#f1c40f"),
    (45, 65, "Elevated", "#e67e22"),
    (65, 85, "High", "#e74c3c"),
    (85, 100, "Extreme", "#8e44ad"),
]

CATEGORY_ORDER = [
    "Volatility",
    "Credit",
    "Rates",
    "Conditions",
    "Equity",
    "Sentiment",
    "Funding",
    "Money Supply",
    "Consumer Credit",
    "FX & Commodities",
    "Labor",
]

# Categories expanded by default in the detail chart section
EXPANDED_BY_DEFAULT = {"Volatility", "Credit", "Rates", "Conditions", "Equity"}
